### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by acidjunk** [ivnsch/clojushop#1]
Hi,

project looks very promising. I'm having a bit of a hard time figuring out which version would be the best to use as a starting point:

https://github.com/huihoo/clojure-shopping
https://github.com/trickyBytes/clojushop
https://github.com/openweb/clojure-shopping

Or your, original, version.

I will be working on a very small shop and want to use the project as an tutorial/learning project into Clojure. Will try to build a reframe GUI for it in the next couple of weeks.

Just wondering if it's would be good to get the forks in sync again.

**Comment by acidjunk** [comment]
FYI

When I try to run the original version: 
```
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
```

Using lein2.7.1 or with temporary allowing insecure downloads:
```
Could not transfer artifact org.clojure:clojure:pom:1.2.0-beta1 from/to clojure (http://build.clojure.org/releases): Access denied to: http://build.clojure.org/releases/org/clojure/clojure/1.2.0-beta1/clojure-1.2.0-beta1.pom , ReasonPhrase:Forbidden.
Could not transfer artifact org.clojure:clojure-contrib:pom:1.2.0-beta1 from/to clojure (http://build.clojure.org/releases): Access denied to: http://build.clojure.org/releases/org/clojure/clojure-contrib/1.2.0-beta1/clojure-contrib-1.2.0-beta1.pom , ReasonPhrase:Forbidden.
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
At the moment the trickyBytes version seems to be the only fork that yields a working stack as it updates the dependencies.

**Comment by ivnsch** [comment]
Thanks for your feedback!

Honestly, I haven't touched Clojure again since I did this, and don't even have Lein installed anymore. I'm not really maintaining this repo.

That said, I'm happy to merge any fixes/improvements.
